################################ Testing hyperparameters #################################################

adam_hyperparameters = {
    'loss_function_name'     : "MSE",
    'optimizer'              : "adam",
    'in_dimension'           : 10,
    'out_dimension'          : 2,
    'mini_batch_percentage'  : [0.2],
    'max_unlucky_epochs'     : 200,
    'max_epochs'             : 300,
    'number_trials'          : 1,
    'n_random_search'        : 12,
    'validation_percentage' : 0.2,
    'validation_type'        : {'method': 'holdout'},
    'target_domain'          : None,
    'lr'                     : [5e-4, 1e-3],
    'lr_decay'               : None,
    'l2'                     : [0.0, 5e-6],
    'adam_decay_rate_1'      : [0.8],
    'adam_decay_rate_2'      : [0.9],
    'hidden_layers'          : [([('tanh',8), ('tanh', 8)],'linear'),],
    'weights_init'           : [{'method': 'normalized'}],
    'print_stats'            : False,
    'additional_metric'      : 'MEE'
}

sgd_hyperparameters = {
    'loss_function_name'     : "MSE",
    'optimizer'              : "SGDN",
    'in_dimension'           : 10,
    'out_dimension'          : 2,
    'mini_batch_percentage'  : 1,
    'max_unlucky_epochs'     : 100,
    'max_epochs'             : 300,
    'number_trials'          : 1,
    'n_random_search'        : 12,
    'validation_percentage' : 0.2,
    'validation_type'        : {'method': 'holdout'},
    'target_domain'          : None,
    'lr'                     : [0.1, 0.2, 0.3, 0.4],
    'lr_decay'               : None,
    'l2'                     : [0],
    'momentum'               : [0.3],
    'hidden_layers'          : [([('tanh',8), ('tanh', 8)],'linear'),],
    'weights_init'           : [{'method': 'normalized'}],
    'print_stats'            : False,
    'additional_metric'      : 'MEE'
}


################################ Final hyperparameters #################################################

adam_hyperparameters1 = {
    'loss_function_name'     : "MSE",
    'optimizer'              : "adam",
    'in_dimension'           : 10,
    'out_dimension'          : 2,
    'mini_batch_percentage'  : [0.2, 0.3],
    'max_unlucky_epochs'     : 200,
    'max_epochs'             : 1200,
    'number_trials'          : 1,
    'n_random_search'        : 36,
    'validation_type'        : {'method': 'kfold', 'k': 5},
    'target_domain'          : None,
    'lr'                     : [5e-4, 1e-3, 4e-3, 6e-3, 8e-3, 1e-2],
    'lr_decay'               : None,
    'l2'                     : [0.0, 5e-6, 1e-5, 5e-5, 1e-4, 5e-4],
    'adam_decay_rate_1'      : [0.8, 0.9],
    'adam_decay_rate_2'      : [0.9, 0.999],
    'hidden_layers'          : [([('tanh',32), ('tanh', 32)],'linear'),
                                ([('relu',32), ('relu', 32)],'linear'),
                                ([('tanh',16), ('tanh', 16)],'linear'),
                                ([('relu',16), ('relu', 16)],'linear'),
                                ([('tanh',16), ('tanh', 16),('tanh',16)],'linear'),
                                ([('relu',16), ('relu', 16),('relu',16)],'linear'),],
    'weights_init'           : [{'method': 'normalized'}, {'method': 'linear', 'range': 0.7}],
    'print_stats'            : False,
    'additional_metric'      : 'MEE'
}

sgd_hyperparameters1 = {
    'loss_function_name'     : "MSE",
    'optimizer'              : "SGDN",
    'in_dimension'           : 10,
    'out_dimension'          : 2,
    'mini_batch_percentage'  : 1,
    'max_unlucky_epochs'     : 100,
    'max_epochs'             : 1200,
    'number_trials'          : 1,
    'n_random_search'        : 36,
    'validation_type'        : {'method': 'kfold', 'k': 5},
    'target_domain'          : None,
    'lr'                     : [5e-4, 1e-3, 4e-3, 6e-3, 8e-3, 1e-2],
    'lr_decay'               : None,
    'l2'                     : [0.0, 5e-6, 1e-5, 5e-5, 1e-4, 5e-4],
    'momentum'               : [0, 0.25, 0.5, 0.75],
    'hidden_layers'          : [([('tanh',32), ('tanh', 32)],'linear'),
                                ([('relu',32), ('relu', 32)],'linear'),
                                ([('tanh',16), ('tanh', 16)],'linear'),
                                ([('relu',16), ('relu', 16)],'linear'),
                                ([('tanh',16), ('tanh', 16),('tanh',16)],'linear'),
                                ([('relu',16), ('relu', 16),('relu',16)],'linear'),],
    'weights_init'           : [{'method': 'normalized'}, {'method': 'linear', 'range': 0.7}],
    'print_stats'            : False,
    'additional_metric'      : 'MEE'
}
